In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:20pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:20pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:20px;}
</style>
"""))

In [2]:
import pandas as pd #파일입력(read_excel), 교차표(crosstab), 원핫인코딩(get_dummies)
import numpy as np
from sklearn.model_selection import train_test_split # 훈련셋과 시험셋 분리함수
from tensorflow.keras.utils import to_categorical #원핫인코딩
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from tensorflow.keras.models import Sequential, save_model,load_model
from tensorflow.keras.layers import Dense,Input,Dropout # dropout은 과적합을 줄이기 위한 방법
import matplotlib.pyplot as plt # 모델 학습과정 살펴보기
from sklearn.metrics import confusion_matrix # 혼동행렬

# 이진분류(로지스틱 회귀분석 )
- 1. 데이터셋 생성 & 전처리
    * 엑셀 -> 데이터프래임 ->?처리(결측치로 전환하여 결측치 처리)-> X,y분리
        -> X변수의 scale조정 -> train_test_split()을 이용하여 학습셋과 테스트셋을 분리
- 2. 모델생성(입력13,타겟1) -과적합 고려 & 학습과정 설정 & 학습
- 3. 모델평가(그래프, 평가, 혼동행렬=교차그래프)
- 4. 모델사용

In [6]:
df=pd.read_excel('data/heart-disease.xlsx'
             #sheet_name='processed.cleveland'
             )
df.head()

   age  sex  cp  treshtbps chol  fbs  restecg  thalach  exang  oldpeak  slope ca hsl  heartDisease
0   63    1   1        145  233    1        2      150      0      2.3      3  0   6             0
1   67    1   4        160  286    0        0      108      1      1.5      2  3   3             1
2   67    1   4        120    ?    0        2      129      1      2.6      2  2   7             1
3   37    1   3        130  250    0        0      187      0      3.5      3  0   3             0
4   41    0   2        130  204    0        2      172      0      1.4      1  0   3             0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           303 non-null    int64
 1   sex           303 non-null    int64
 2   cp            303 non-null    int64
 3   treshtbps     303 non-null    int64
 4   chol          303 non-null    object
 5   fbs           303 non-null    int64
 6   restecg       303 non-null    int64
 7   thalach       303 non-null    int64
 8   exang         303 non-null    int64
 9   oldpeak       303 non-null    float64
 10  slope         303 non-null    int64
 11  ca            303 non-null    object
 12  hsl           303 non-null    object
 13  heartDisease  303 non-null    int64
dtypes: float64(1), int64(10), object(3)
memory usage: 33.3+ KB

In [8]:
df.isnull().sum()

age             0
sex             0
cp              0
treshtbps       0
chol            0
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              0
hsl             0
heartDisease    0
dtype: int64

In [11]:
df.isin(['?']).sum()

age             0
sex             0
cp              0
treshtbps       0
chol            1
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              4
hsl             2
heartDisease    0
dtype: int64

In [12]:
df[(df['chol']=='?') |(df['ca']=='?') | (df['hsl']=='?')]

     age  sex  cp  treshtbps chol  fbs  restecg  thalach  exang  oldpeak  slope ca hsl  heartDisease
2     67    1   4        120    ?    0        2      129      1      2.6      2  2   7             1
87    53    0   3        128  216    0        2      115      0      0.0      1  0   ?             0
166   52    1   3        138  223    0        0      169      0      0.0      1  ?   3             0
192   43    1   4        132  247    1        2      143      1      0.1      2  ?   7             1
266   52    1   4        128  204    1        0      156      1      1.0      2  0   ?             1
287   58    1   2        125  220    0        0      144      0      0.4      2  ?   7             0
302   38    1   3        138  175    0        0      173      0      0.0      1  ?   3             0

In [18]:
# ?를 결측치로 대체 => 결측치 삭제
df=df.replace('?',np.nan)
df[(df['chol']=='?') |(df['ca']=='?') | (df['hsl']=='?')]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [22]:
# 결측치가 포함된 데이터 추출
df[df['chol'].isna() | df['ca'].isna() | df['hsl'].isna()]
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [23]:
# 결측치 처리 : 삭제(dropna) cf.fillna() apply()
df.dropna(how='any',inplace=True) #결측치가 한열이라도 있으면 삭제
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [age, sex, cp, treshtbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, hsl, heartDisease]
Index: []

In [24]:
df.isna().sum()

age             0
sex             0
cp              0
treshtbps       0
chol            0
fbs             0
restecg         0
thalach         0
exang           0
oldpeak         0
slope           0
ca              0
hsl             0
heartDisease    0
dtype: int64

In [26]:
df.shape

(296, 14)

In [30]:
# 타겟변수 확인
df['heartDisease'].value_counts(normalize=True)

0    0.540541
1    0.459459
Name: heartDisease, dtype: float64

In [35]:
# X,y분리 -> X변수의 scale조정 
X = df.iloc[:,:-1].values # 맨마지막 열을 제외한 부분을 numpy배열
y = df.iloc[:,-1:].values # 2차원 numpy 배열
X.shape, y.shape

((296, 13), (296, 1))

In [ ]:
# X변수의 scale 2조정
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print('원 데이터:' X[0])
print('스케일 조정 데이터:',scaled_X[0]

In [36]:
# scaled_X와 y를 학습데이터셋 : 테스트셋 = 8:2
X_train, X_test, y_train, y_test = train_test_split(scaled_X,
                                                y,
                                                test_size=0.2,
                                                random_state=7,
                                                stratify=y   )

NameError: name 'scaled_X' is not defined

In [37]:
# 심장병 음성/양성 비율(y,y_train,y_test)
print(pd.DataFrame(y).value_counts(normalize=True))
print(pd.DataFrame(y_train).value_counts(normalize=True))
print(pd.DataFrame(y_test).value_counts(normalize=True))

0    0.540541
1    0.459459
dtype: float64

NameError: name 'y_train' is not defined

## 2.모델생성 &학습과정 설정 &학습